version: '3.7'
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - /var/local/docker/volumes/nexus:/nexus-data
    ports:
      - "8091:8081"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.20'
          memory: 512M
      mode: replicated
      replicas: 1
    networks:
      - nexus
networks:
  nexus:

