version: '3.7'
services:
  artifactory:
    image: mattgruter/artifactory
    volumes:
      - /var/local/docker/volumes/artifactory/data:/artifactory/data
      - /var/local/docker/volumes/artifactory/logs:/artifactory/logs
      - /var/local/docker/volumes/artifactory/backup:/artifactory/backup
    ports:
      - "8091:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.20'
          memory: 512M
      mode: replicated
      replicas: 1
    networks:
      - artifactory
networks:
  artifactory:

